# Generated by Django 3.1.6 on 2021-03-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
