# Generated by Django 3.1.6 on 2021-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_auto_20210301_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(upload_to='student_images/'),
        ),
    ]
