# Generated by Django 3.1.6 on 2021-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_auto_20210301_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(upload_to='student_images/%Y/%m/'),
        ),
    ]
