# Generated by Django 3.1.6 on 2021-03-01 07:36

from django.db import migrations, models
import myapp2.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0007_auto_20210301_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.FileField(upload_to=myapp2.models.overwrite),
        ),
    ]
