# Generated by Django 3.1.6 on 2021-03-03 06:36

from django.db import migrations, models
import myapp2.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_auto_20210301_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, upload_to=myapp2.models.overwrite),
        ),
    ]
